### PR TITLE
adding 05-linking-accounts with LinkAccountService and LinkedAccounts…

### PR DESCRIPTION
**Pull request by flaviogranero**
…List/ListAccountItem components

### CODE REVIEW

**Comment by alemata** [comment]
👍  @ntotten

**Comment by flaviogranero** [comment]
@mpaktiti this is ready

**Comment by chenkie** [comment]
Thanks. There are a couple issues to fix :)
* Bootstrap isn't included in `package.json`
* I'm getting a bunch of `Unknown prop` errors in the console http://d.pr/i/19aME

**Comment by chenkie** [comment]
We also need a more explicit check when mapping over the `identities` to account for error cases.For example, this is what I got back:

```
identities = {
  error: "Bad Request",
  errorCode: "operation_not_supported",
  message: "Main identity and the new one are the same.",
  statusCode: 400
}
```

http://d.pr/i/OBsn

**Comment by flaviogranero** [comment]
hi @chenkie you're right about missing bootstrap, I'll be fixing in all PRs. About the warnings you see in the console, it's an issue in react-bootstrap library https://github.com/react-bootstrap/react-bootstrap/issues/1994 with React 15.2.0
seems like it's already fixed, but not released. We have the option to fix a previous version of React js in our package.json, or wait for a new react-bootstrap release. what do you think?

**Comment by flaviogranero** [comment]
@chenkie the other reported issues are fixed, let me know what do you prefer for react-bootstrap warnings

**Comment by chenkie** [comment]
Awesome, looks good @flaviogranero thanks.

We'll leave the React deps as they are. Sounds like a new react-bootstrap release will be happening very quickly.

Thanks

**Pull request merged**
