### PR TITLE
adding 03-Session-Handling, renaming 03-User-Profile to 04-User-Profile

### PR DESCRIPTION
**Pull request by flaviogranero**

### CODE REVIEW

**Comment by flaviogranero** [comment]
@alemata please take a look

**Comment by mpaktiti** [comment]
@flaviogranero @alemata
Please notify me as well when this is reviewed from your side. This applies to all samples.

**Comment by flaviogranero** [comment]
@alemata just updated this, could you take a look?

**Comment by alemata** [comment]
👍  @chenkie @mpaktiti

**Comment by mpaktiti** [comment]
Currently the [Session Handling](https://auth0.com/docs/quickstart/spa/react/03-session-handling) page points to the [login sample](https://github.com/auth0-samples/auth0-react-sample/tree/master/01-Login)

PR that fixes this issue: https://github.com/auth0/docs/pull/1792

To be merged when this PR is merged and the correct sample is in place.

**Comment by flaviogranero** [comment]
@chenkie could we have this one merged as well?

**Pull request merged**
